### ISSUE TITLE
Colspan cells are improperly affected by colwidth

### ISSUE THREAD

**Issue by jedateach** [jamestalmage/cli-table2#19]
If you have a col with on column1, and you colspan two columns, then the cell will wrap at the first column's colwidth.

Might be better to wrap at col1 width + col2 width? Would need to consider cols with null widths however.

**Comment by jamestalmage** [comment]
Sure, that's definitely a bug.

column widths are knowable (they get computed at some point), it should be easy to avoid `null` widths.

PR Welcome
