### ISSUE TITLE
This project appears to introduce ~532 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [jamestalmage/cli-table2#25]
own files that may be included by mistake:
----

- [x] examples
- [x] test

dependencies that may need investigation (499):
---

 - [ ] colors      25
 - [x] lodash     434 (often times, a subset of lodash is sufficient, and many such lodash subsets are individual dependencies)
 - [ ] string-width      39

**Comment by jamestalmage** [comment]
With #26, and #27 merged, would you call this fixed?

I don't see an alternative to using colors, though `string-width` seems to have a surprising amount of dependencies.

**Comment by jamestalmage** [comment]
`string-width` has only three dependencies. I don't think that's a big deal. I think we've whittled it down enough.

**Comment by sindresorhus** [comment]
string-width@2 now only has one dependency, but requires Node.js 4.
