### ISSUE TITLE
Publish latest master?

### ISSUE THREAD

**Issue by siddharthkp** [jamestalmage/cli-table2#28]
Hey, noticed that the version on github is a lot smaller than the on published on npm. (Might be because of lodash)

Excellent optimisation!

When are you publishing this smaller version? 😄

**Comment by Turbo87** [comment]
as you can see in https://github.com/jamestalmage/cli-table2/issues/43 we have forked the project to https://github.com/cli-table/cli-table3 and have published a new `cli-table3@0.4.0` release for the current `master` branch :)

**Comment by siddharthkp** [comment]
That's great, thanks 👍
